$('#teamSlider').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    dots:true,
    autoplay:true,
    autoplayTimeout:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})

$('#keySlider').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    autoplay:false,
    autoplayTimeout:1000,
    responsive:{
        0:{
            items:1,
            dots:true,
        },
        600:{
            items:2,
            dots:true,
        },
        1000:{
            items:4,
            dots:false,
            mouseDrag:false,
            touchDrag:false,
        }
    }
})

AOS.init();